"""The `sponsifable` command.

    sponsifable                     serve the app on this machine
    sponsifable seal DEAL FILE      establish rights on a won deal, before delivery
    sponsifable verify FILE         check a downloaded ad against your seals
    sponsifable log DEAL            record when a deal's overlay was on air, from OBS
    sponsifable report DEAL         sign what the log says was on air, for the sponsor
    sponsifable key --ssh PATH      choose the SSH key that signs your receipts
    sponsifable setup               download the watermark model now
"""

from __future__ import annotations

import argparse
import getpass
import importlib.util
import json
import os
import secrets
import sys
from datetime import date
from pathlib import Path

from . import __version__, keys, ledger, manifest, sshsig, workspace
from .timestamp import DEFAULT_TSA


def _iso(value: str) -> date:
    try:
        return date.fromisoformat(value)
    except ValueError as error:
        raise argparse.ArgumentTypeError(f"{value!r} is not a YYYY-MM-DD date") from error


_WORKSPACE_HELP = "the workspace file (default: the one the app saves to, under ~/.sponsifable)"


def _workspace(args: argparse.Namespace, home: Path) -> Path:
    """The file named with --workspace, or the one the server serves."""
    return args.workspace or workspace.default_path(home)


def _pick_up_line(args: argparse.Namespace, path: Path, then: str) -> str:
    """What to tell the creator after the CLI wrote into a workspace."""
    if args.workspace is None:
        return "The app picks this up on its own."
    return f"Then import {path} into the app {then}."


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="sponsifable", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--version", action="version", version=f"sponsifable {__version__}")
    sub = parser.add_subparsers(dest="command")

    serve = sub.add_parser("serve", help="serve the app on 127.0.0.1 (the default)")
    serve.add_argument("--port", type=int, default=5180)
    serve.add_argument("--no-browser", action="store_true")
    serve.add_argument("--workspace", type=Path, help=_WORKSPACE_HELP)
    serve.add_argument("--api-only", action="store_true", help="serve only /api, for development beside Vite")
    serve.add_argument("--allow-origin", action="append", default=[], metavar="URL",
                       help="also accept writes from this origin, e.g. http://localhost:5180 for Vite")

    seal = sub.add_parser("seal", help="watermark and timestamp a deal's asset, before delivery")
    seal.add_argument("deal", help="deal id, shown in the app's Deals tab, e.g. dl-104")
    seal.add_argument("file", type=Path, help="the finished asset (PNG, JPEG or WebP)")
    seal.add_argument("--workspace", type=Path, help=_WORKSPACE_HELP)
    seal.add_argument("--source", required=True, choices=sorted(manifest.SOURCE_TYPES),
                      help="how the asset was made: camera capture, made in software, generated by a model, or a mix")
    seal.add_argument("--out", type=Path, help="where to write the sealed copy")
    seal.add_argument("--tsa", default=DEFAULT_TSA, help="RFC 3161 timestamp authority")
    seal.add_argument("--no-c2pa", action="store_true", help="skip the C2PA manifest")
    seal.add_argument("--yes", action="store_true", help="skip the typed confirmation, for scripts")

    verify = sub.add_parser("verify", help="check a downloaded ad against your seals")
    verify.add_argument("file", type=Path, help="the ad, as downloaded from an ad library")
    verify.add_argument("--started", type=_iso, required=True, help="the date the ad library says it started running")
    verify.add_argument("--seen", type=_iso, default=date.today(), help="the date you saw it still running (default today)")
    verify.add_argument("--source", default="", help="where you found it, e.g. the ad library link")
    verify.add_argument("--workspace", type=Path, help=f"{_WORKSPACE_HELP}; a verified sighting is recorded there")

    log = sub.add_parser("log", help="record when a deal's placement was on air, from OBS")
    log.add_argument("deal", help="deal id, shown in the app's Deals tab, e.g. dl-104")
    log.add_argument("--source", action="append", metavar="NAME",
                     help="a browser source to watch, by its name in OBS; repeat for several "
                          "(default: every placement's usual name, watching those OBS has)")
    log.add_argument("--url", default="ws://127.0.0.1:4455", help="where OBS's WebSocket server is listening")
    log.add_argument("--poll", type=float, default=2.0, help="seconds of quiet before asking OBS directly")
    log.add_argument("--workspace", type=Path, help=_WORKSPACE_HELP)

    rep = sub.add_parser("report", help="sign a delivery report from the on-air log, for the sponsor")
    rep.add_argument("deal", help="deal id, shown in the app's Deals tab, e.g. dl-104")
    rep.add_argument("--vod", default="", help="the recording's address, so the sponsor can open it at the offsets")
    rep.add_argument("--workspace", type=Path, help=_WORKSPACE_HELP)

    key = sub.add_parser("key", help="choose or show the SSH key that signs your receipts")
    key.add_argument("--ssh", type=Path, help="path to your SSH private key, e.g. ~/.ssh/id_ed25519")
    sub.add_parser("setup", help="download the watermark model now rather than mid-seal")
    return parser


def _watermark_installed() -> bool:
    """Checked before any prompt, so a missing extra never surfaces mid-seal."""
    if importlib.util.find_spec("trustmark") is not None:
        return True
    print("Sealing and verifying need the watermark model, which is an optional extra because it brings "
          "PyTorch with it. Install it with:\n  pipx install --force 'sponsifable[seal]'", file=sys.stderr)
    return False


def _seal(args: argparse.Namespace, home: Path) -> int:
    from . import sealing
    from .timestamp import remote
    from .watermark import TrustMarkWatermarker

    if not _watermark_installed():
        return 1
    path = _workspace(args, home)
    if not path.exists():
        print(f"Not sealed: there is no workspace at {path}. Run `sponsifable serve` and open the app once, "
              "or name an exported file with --workspace.", file=sys.stderr)
        return 1
    try:
        signer = keys.signer_for(home)
        p = sealing.plan(path, args.deal, args.file, args.out, args.source, home)
    except (keys.NoKey, sealing.SealRefused, FileNotFoundError, ValueError) as error:
        print(f"Not sealed: {error}.", file=sys.stderr)
        return 1

    print(p.summary(args.tsa, sshsig.fingerprint(signer.public_key)), "\n")
    if not args.yes and input("Type 'seal' to proceed: ").strip() != "seal":
        print("Nothing was sealed.")
        return 1

    creator = workspace.load(path).get("profile", {}).get("name", "")
    deps = sealing.Deps(TrustMarkWatermarker(), remote(args.tsa), signer, lambda: secrets.token_bytes(16),
                        date.today().isoformat(), home, embed_manifest=not args.no_c2pa)
    try:
        record = sealing.execute(p, deps, creator)
    except sealing.SealRefused as error:
        print(f"Not sealed: {error}.", file=sys.stderr)
        return 1

    serial = record["receipt"]["serial"]
    folder = ledger.ledger_dir(home)
    print(f"\nSealed. Serial {serial}, timestamped {record['timestamp']['time']}.")
    print(f"  Deliver:          {p.out}")
    print(f"  Send the sponsor: {serial}.txt, {serial}.receipt.json and {serial}.receipt.json.sig")
    print(f"                    from {folder}")
    print(f"  {_pick_up_line(args, path, 'and set the delivery date')}")
    return 0


def _print_finding(finding) -> None:  # noqa: ANN001 - Finding, imported lazily
    if finding.kind == "no-mark":
        print("No watermark decoded. That proves nothing either way: it may have been stripped, "
              "lost to reframing, or never there.")
        for serial, distance in finding.resembles:
            print(f"  It resembles the asset sealed as {serial} (pHash distance {distance}). "
                  "Resemblance is a reason to look closer, not evidence.")
    elif finding.kind == "unknown-serial":
        print(f"A watermark decoded to serial {finding.serial}, which is not in your ledger. "
              "It is not one of your seals.")
    else:
        claim = finding.claim
        print(f"Serial {finding.serial}: deal {finding.deal_id}.")
        for label, ok, why in claim.checks:
            print(f"  {'pass' if ok else 'FAIL'}  {label}: {why}")
        if claim.holds:
            permitted = "unlimited" if claim.permitted is None else f"{claim.permitted} days"
            print(f"  Ran {claim.days_run} days against {permitted} permitted.", end=" ")
            print(f"Over by {claim.overrun_days} days." if claim.overrun_days else "Within terms.")
        else:
            print("  The claim does not hold, so no overrun is reported and nothing is recorded.")
        print("  The timestamp's signature was checked against the certificate the authority embedded; "
              "the chain to a trusted root was not walked.")
    if finding.manifest_licence:
        print(f"  A C2PA manifest survived, stating: {finding.manifest_licence}")


def _verify(args: argparse.Namespace, home: Path) -> int:
    from .verifying import record_sighting, verify
    from .watermark import TrustMarkWatermarker

    if not _watermark_installed():
        return 1
    finding = verify(args.file, args.started, args.seen, TrustMarkWatermarker(), home)
    _print_finding(finding)
    path = _workspace(args, home)
    if path.exists() and record_sighting(path, finding, args.started, args.seen, args.source):
        print(f"\nRecorded as a verified sighting in {path}. {_pick_up_line(args, path, 'to price the overrun')}")
    return 0 if finding.kind == "claim" and finding.claim and finding.claim.holds else 2


def _log_deal(args: argparse.Namespace, home: Path) -> dict | None:
    """The deal this log belongs to, or None with the reason printed."""
    path = _workspace(args, home)
    if not path.exists():
        print(f"No workspace at {path}. Run `sponsifable serve` and open the app once.", file=sys.stderr)
        return None
    deal = workspace.find_deal(workspace.load(path), args.deal)
    if deal is None:
        print(f"No deal {args.deal} in {path}.", file=sys.stderr)
        return None
    if deal.get("outcome") != "won":
        print(f"{args.deal} is not a won deal, so there is nothing to deliver.", file=sys.stderr)
        return None
    return deal


def _log(args: argparse.Namespace, home: Path) -> int:
    """Follow OBS and append every on-air transition to the deal's log."""
    from websockets.sync.client import connect

    from . import onair
    from .obs import Obs

    if _log_deal(args, home) is None:
        return 1
    path = onair.log_path(home, args.deal)
    password = os.environ.get("OBS_WEBSOCKET_PASSWORD") or getpass.getpass("OBS WebSocket password (blank if none): ") or None

    def write(line: dict) -> None:
        onair.append(path, line)
        print(json.dumps(line, ensure_ascii=False), flush=True)

    session = onair.Session(args.deal, args.source or list(onair.CONVENTIONAL_SOURCES), write)
    print(f"Watching OBS for {args.deal}. Ctrl+C to stop. Appending to {path}")
    try:
        with connect(args.url, open_timeout=5) as socket:
            obs = Obs(socket, session.event)
            obs.identify(password)
            onair.follow(obs, session, args.poll)
    except KeyboardInterrupt:
        session.end()
    except (OSError, RuntimeError) as error:
        print(f"OBS: {error}. Is the WebSocket server switched on, under Tools?", file=sys.stderr)
        return 1
    summary = onair.delivery(onair.read_log(path))
    minutes = summary.total_seconds / 60
    print(f"\nOn air {minutes:.1f} minutes across {len(summary.intervals)} intervals.")
    for placement in summary.placements:
        print(f"  {placement.source}: {placement.total_seconds / 60:.1f} minutes")
    if summary.disagreements:
        print(f"{summary.disagreements} polls disagreed with OBS's events. The report will say so.")
    return 0


def _write_report(home: Path, deal: dict, delivery, log_path: Path, vod: str, creator: str, signer) -> tuple[dict, list[Path]]:  # noqa: ANN001
    """Build, sign and write the report. Raises keys.NoKey if signing fails."""
    import hashlib
    from datetime import datetime, timezone

    from . import receipt
    from . import report as reports

    body = reports.build_report(
        deal, delivery,
        creator=creator,
        public_key=sshsig.normalise(signer.public_key),
        reported_at=datetime.now(timezone.utc).isoformat(timespec="seconds"),
        log_sha256=hashlib.sha256(log_path.read_bytes()).hexdigest(),
        vod_url=vod,
    )
    signed = receipt.canonical(body)
    signature = signer.sign(signed, reports.NAMESPACE)
    identity = keys.principal(creator)
    notice = reports.sponsor_notice(
        body,
        fingerprint=sshsig.fingerprint(body["publicKey"]),
        allowed_signers=keys.allowed_signers_line(identity, body["publicKey"], reports.NAMESPACE),
        identity=identity,
    )
    return body, reports.write(home, body, signature, notice, signed)


def _report(args: argparse.Namespace, home: Path) -> int:
    """Fold the on-air log, sign it, and write the sponsor's files."""
    from . import onair
    from . import report as reports

    deal = _log_deal(args, home)
    if deal is None:
        return 1
    log_path = onair.log_path(home, args.deal)
    delivery = onair.delivery(onair.read_log(log_path))
    if not delivery.intervals and delivery.open_since is None:
        print(f"Nothing on air is recorded for {args.deal}. Run `sponsifable log {args.deal}` during the stream first.",
              file=sys.stderr)
        return 1
    creator = workspace.load(_workspace(args, home)).get("profile", {}).get("name", "")
    try:
        body, paths = _write_report(home, deal, delivery, log_path, args.vod, creator, keys.signer_for(home))
    except keys.NoKey as error:
        print(f"Not signed: {error}.", file=sys.stderr)
        return 1
    minutes = body["totalSeconds"] / 60
    print(f"On air {minutes:.1f} minutes across {len(body['intervals'])} intervals. "
          f"Signed with {sshsig.fingerprint(body['publicKey'])}.")
    if body["disagreements"] or body["openSince"]:
        print("The report names what the log could not settle; read the .txt before sending it.")
    print(f"  Send the sponsor: {', '.join(p.name for p in paths)}")
    print(f"                    from {reports.reports_dir(home)}")
    return 0


def _key(args: argparse.Namespace, home: Path) -> int:
    """Choose or show the SSH key that signs receipts."""
    try:
        if args.ssh:
            keys.set_key(home, args.ssh.expanduser())
        public = keys.signer_for(home).public_key
    except keys.NoKey as error:
        print(f"{error}.", file=sys.stderr)
        return 1
    print(f"Signing key:  {keys.configured_key(home)}")
    print(f"Fingerprint:  {sshsig.fingerprint(public)}")
    print("\nWrite the fingerprint into your contracts. It is how a sponsor knows a receipt is yours.")
    print("If this key is on your GitHub account, a sponsor can also match it at github.com/<you>.keys.")
    return 0


def main(argv: list[str] | None = None) -> None:
    """Entry point."""
    sys.stdout.reconfigure(encoding="utf-8")
    args = _parser().parse_args(argv)
    home = ledger.home_dir()
    if args.command in (None, "serve"):
        from .serve import serve

        serve(
            getattr(args, "workspace", None) or workspace.default_path(home),
            getattr(args, "port", 5180),
            open_browser=not getattr(args, "no_browser", False),
            api_only=getattr(args, "api_only", False),
            allowed_origins=frozenset(getattr(args, "allow_origin", [])),
            home=home,
        )
    elif args.command == "seal":
        sys.exit(_seal(args, home))
    elif args.command == "verify":
        sys.exit(_verify(args, home))
    elif args.command == "log":
        sys.exit(_log(args, home))
    elif args.command == "report":
        sys.exit(_report(args, home))
    elif args.command == "key":
        sys.exit(_key(args, home))
    elif args.command == "setup":
        if not _watermark_installed():
            sys.exit(1)
        from .watermark import prefetch

        prefetch()
        print("Watermark model ready.")
